name: flutter_plain_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_appbar: ^1.3.2
  flutter_rebuildable: ^1.0.0
  flutter_svg: ^2.0.17
  flutter_touch_ripple: ^2.5.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/svgs/
    - assets/images/